/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type { AssociateAccountStockDto } from '../schemas';

import { orvalClient } from '../../lib/orval/orval.client';
import type { ErrorType, BodyType } from '../../lib/orval/orval.client';

/**
 * Returns all assets of an account with prices updated in real time via the Brapi API.
 * @summary List of portfolio shares.
 */
export const listAllStocks = (accountId: string, signal?: AbortSignal) => {
	return orvalClient<Blob>({
		url: `/accounts/${accountId}/stocks`,
		method: 'GET',
		responseType: 'blob',
		signal,
	});
};

export const getListAllStocksQueryKey = (accountId: string) => {
	return [`/accounts/${accountId}/stocks`] as const;
};

export const getListAllStocksQueryOptions = <
	TData = Awaited<ReturnType<typeof listAllStocks>>,
	TError = ErrorType<unknown>,
>(
	accountId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAllStocks>>, TError, TData>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getListAllStocksQueryKey(accountId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllStocks>>> = ({
		signal,
	}) => listAllStocks(accountId, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!accountId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof listAllStocks>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAllStocksQueryResult = NonNullable<
	Awaited<ReturnType<typeof listAllStocks>>
>;
export type ListAllStocksQueryError = ErrorType<unknown>;

export function useListAllStocks<
	TData = Awaited<ReturnType<typeof listAllStocks>>,
	TError = ErrorType<unknown>,
>(
	accountId: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAllStocks>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listAllStocks>>,
					TError,
					Awaited<ReturnType<typeof listAllStocks>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllStocks<
	TData = Awaited<ReturnType<typeof listAllStocks>>,
	TError = ErrorType<unknown>,
>(
	accountId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAllStocks>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listAllStocks>>,
					TError,
					Awaited<ReturnType<typeof listAllStocks>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllStocks<
	TData = Awaited<ReturnType<typeof listAllStocks>>,
	TError = ErrorType<unknown>,
>(
	accountId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAllStocks>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List of portfolio shares.
 */

export function useListAllStocks<
	TData = Awaited<ReturnType<typeof listAllStocks>>,
	TError = ErrorType<unknown>,
>(
	accountId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAllStocks>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListAllStocksQueryOptions(accountId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Links a financial asset and the quantity purchased to a specific account.
 * @summary Associates an stock with an account.
 */
export const associateStock = (
	accountId: string,
	associateAccountStockDto: BodyType<AssociateAccountStockDto>,
	signal?: AbortSignal
) => {
	return orvalClient<void>({
		url: `/accounts/${accountId}/stocks`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: associateAccountStockDto,
		signal,
	});
};

export const getAssociateStockMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof associateStock>>,
		TError,
		{ accountId: string; data: BodyType<AssociateAccountStockDto> },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof associateStock>>,
	TError,
	{ accountId: string; data: BodyType<AssociateAccountStockDto> },
	TContext
> => {
	const mutationKey = ['associateStock'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof associateStock>>,
		{ accountId: string; data: BodyType<AssociateAccountStockDto> }
	> = props => {
		const { accountId, data } = props ?? {};

		return associateStock(accountId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type AssociateStockMutationResult = NonNullable<
	Awaited<ReturnType<typeof associateStock>>
>;
export type AssociateStockMutationBody = BodyType<AssociateAccountStockDto>;
export type AssociateStockMutationError = ErrorType<void>;

/**
 * @summary Associates an stock with an account.
 */
export const useAssociateStock = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof associateStock>>,
			TError,
			{ accountId: string; data: BodyType<AssociateAccountStockDto> },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof associateStock>>,
	TError,
	{ accountId: string; data: BodyType<AssociateAccountStockDto> },
	TContext
> => {
	return useMutation(getAssociateStockMutationOptions(options), queryClient);
};
