/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type {
	AuthResponseDto,
	CreateUserDto,
	ErrorResponseDto,
	LoginDto,
	UserDto,
} from '../schemas';

import { orvalClient } from '../../lib/orval/orval.client';
import type { ErrorType, BodyType } from '../../lib/orval/orval.client';

/**
 * Registers a new user and returns a JWT token for authentication.
 * @summary Create/Register a new user.
 */
export const register = (
	createUserDto: BodyType<CreateUserDto>,
	signal?: AbortSignal
) => {
	return orvalClient<AuthResponseDto>({
		url: `/auth/register`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: createUserDto,
		signal,
	});
};

export const getRegisterMutationOptions = <
	TError = ErrorType<ErrorResponseDto>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof register>>,
		TError,
		{ data: BodyType<CreateUserDto> },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof register>>,
	TError,
	{ data: BodyType<CreateUserDto> },
	TContext
> => {
	const mutationKey = ['register'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof register>>,
		{ data: BodyType<CreateUserDto> }
	> = props => {
		const { data } = props ?? {};

		return register(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
	Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = BodyType<CreateUserDto>;
export type RegisterMutationError = ErrorType<ErrorResponseDto>;

/**
 * @summary Create/Register a new user.
 */
export const useRegister = <
	TError = ErrorType<ErrorResponseDto>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof register>>,
			TError,
			{ data: BodyType<CreateUserDto> },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof register>>,
	TError,
	{ data: BodyType<CreateUserDto> },
	TContext
> => {
	return useMutation(getRegisterMutationOptions(options), queryClient);
};
/**
 * Invalidates the current Bearer token. Requires an active session.
 * @summary Logout user
 */
export const logout = (signal?: AbortSignal) => {
	return orvalClient<void>({ url: `/auth/logout`, method: 'POST', signal });
};

export const getLogoutMutationOptions = <
	TError = ErrorType<ErrorResponseDto>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof logout>>,
		TError,
		void,
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof logout>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ['logout'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof logout>>,
		void
	> = () => {
		return logout();
	};

	return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
	Awaited<ReturnType<typeof logout>>
>;

export type LogoutMutationError = ErrorType<ErrorResponseDto>;

/**
 * @summary Logout user
 */
export const useLogout = <
	TError = ErrorType<ErrorResponseDto>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof logout>>,
			TError,
			void,
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof logout>>,
	TError,
	void,
	TContext
> => {
	return useMutation(getLogoutMutationOptions(options), queryClient);
};
/**
 * Validates credentials and generates a Bearer token to authenticate subsequent requests.
 * @summary Log in and receive the JWT token.
 */
export const login = (loginDto: BodyType<LoginDto>, signal?: AbortSignal) => {
	return orvalClient<AuthResponseDto>({
		url: `/auth/login`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: loginDto,
		signal,
	});
};

export const getLoginMutationOptions = <
	TError = ErrorType<ErrorResponseDto>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof login>>,
		TError,
		{ data: BodyType<LoginDto> },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof login>>,
	TError,
	{ data: BodyType<LoginDto> },
	TContext
> => {
	const mutationKey = ['login'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof login>>,
		{ data: BodyType<LoginDto> }
	> = props => {
		const { data } = props ?? {};

		return login(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
	Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = BodyType<LoginDto>;
export type LoginMutationError = ErrorType<ErrorResponseDto>;

/**
 * @summary Log in and receive the JWT token.
 */
export const useLogin = <
	TError = ErrorType<ErrorResponseDto>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof login>>,
			TError,
			{ data: BodyType<LoginDto> },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof login>>,
	TError,
	{ data: BodyType<LoginDto> },
	TContext
> => {
	return useMutation(getLoginMutationOptions(options), queryClient);
};
/**
 * Extracts user data from the JWT token provided in the Authorization header.
 * @summary Get current authenticated user
 */
export const me = (signal?: AbortSignal) => {
	return orvalClient<UserDto>({ url: `/auth/me`, method: 'GET', signal });
};

export const getMeQueryKey = () => {
	return [`/auth/me`] as const;
};

export const getMeQueryOptions = <
	TData = Awaited<ReturnType<typeof me>>,
	TError = ErrorType<ErrorResponseDto>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getMeQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof me>>> = ({ signal }) =>
		me(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof me>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MeQueryResult = NonNullable<Awaited<ReturnType<typeof me>>>;
export type MeQueryError = ErrorType<ErrorResponseDto>;

export function useMe<
	TData = Awaited<ReturnType<typeof me>>,
	TError = ErrorType<ErrorResponseDto>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof me>>,
					TError,
					Awaited<ReturnType<typeof me>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMe<
	TData = Awaited<ReturnType<typeof me>>,
	TError = ErrorType<ErrorResponseDto>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof me>>,
					TError,
					Awaited<ReturnType<typeof me>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMe<
	TData = Awaited<ReturnType<typeof me>>,
	TError = ErrorType<ErrorResponseDto>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current authenticated user
 */

export function useMe<
	TData = Awaited<ReturnType<typeof me>>,
	TError = ErrorType<ErrorResponseDto>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getMeQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
