/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from '@tanstack/react-query';

import type { CreateUserDto, LoginDto } from '../schemas';

import { orvalClient } from '../../lib/orval/orval.client';
import type { ErrorType, BodyType } from '../../lib/orval/orval.client';

/**
 * @summary Create/Register a new user.
 */
export const register = (
	createUserDto: BodyType<CreateUserDto>,
	signal?: AbortSignal
) => {
	return orvalClient<void>({
		url: `/auth/register`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: createUserDto,
		signal,
	});
};

export const getRegisterMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof register>>,
		TError,
		{ data: BodyType<CreateUserDto> },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof register>>,
	TError,
	{ data: BodyType<CreateUserDto> },
	TContext
> => {
	const mutationKey = ['register'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof register>>,
		{ data: BodyType<CreateUserDto> }
	> = props => {
		const { data } = props ?? {};

		return register(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
	Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = BodyType<CreateUserDto>;
export type RegisterMutationError = ErrorType<unknown>;

/**
 * @summary Create/Register a new user.
 */
export const useRegister = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof register>>,
			TError,
			{ data: BodyType<CreateUserDto> },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof register>>,
	TError,
	{ data: BodyType<CreateUserDto> },
	TContext
> => {
	return useMutation(getRegisterMutationOptions(options), queryClient);
};
/**
 * Validates credentials and generates a Bearer token to authenticate subsequent requests.
 * @summary Log in and receive the JWT token.
 */
export const login = (loginDto: BodyType<LoginDto>, signal?: AbortSignal) => {
	return orvalClient<Blob>({
		url: `/auth/login`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: loginDto,
		responseType: 'blob',
		signal,
	});
};

export const getLoginMutationOptions = <
	TError = ErrorType<Blob>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof login>>,
		TError,
		{ data: BodyType<LoginDto> },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof login>>,
	TError,
	{ data: BodyType<LoginDto> },
	TContext
> => {
	const mutationKey = ['login'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof login>>,
		{ data: BodyType<LoginDto> }
	> = props => {
		const { data } = props ?? {};

		return login(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
	Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = BodyType<LoginDto>;
export type LoginMutationError = ErrorType<Blob>;

/**
 * @summary Log in and receive the JWT token.
 */
export const useLogin = <TError = ErrorType<Blob>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof login>>,
			TError,
			{ data: BodyType<LoginDto> },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof login>>,
	TError,
	{ data: BodyType<LoginDto> },
	TContext
> => {
	return useMutation(getLoginMutationOptions(options), queryClient);
};
