/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from '@tanstack/react-query';

import type { CreateStockDto } from '../schemas';

import { orvalClient } from '../../lib/orval/orval.client';
import type { ErrorType, BodyType } from '../../lib/orval/orval.client';

/**
 * Adds a ticker (ex: PETR4) to the system's database.
 * @summary Register a new stock.
 */
export const createStock = (
	createStockDto: BodyType<CreateStockDto>,
	signal?: AbortSignal
) => {
	return orvalClient<void>({
		url: `/stocks`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: createStockDto,
		signal,
	});
};

export const getCreateStockMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createStock>>,
		TError,
		{ data: BodyType<CreateStockDto> },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createStock>>,
	TError,
	{ data: BodyType<CreateStockDto> },
	TContext
> => {
	const mutationKey = ['createStock'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createStock>>,
		{ data: BodyType<CreateStockDto> }
	> = props => {
		const { data } = props ?? {};

		return createStock(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateStockMutationResult = NonNullable<
	Awaited<ReturnType<typeof createStock>>
>;
export type CreateStockMutationBody = BodyType<CreateStockDto>;
export type CreateStockMutationError = ErrorType<unknown>;

/**
 * @summary Register a new stock.
 */
export const useCreateStock = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createStock>>,
			TError,
			{ data: BodyType<CreateStockDto> },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof createStock>>,
	TError,
	{ data: BodyType<CreateStockDto> },
	TContext
> => {
	return useMutation(getCreateStockMutationOptions(options), queryClient);
};
