/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type { ErrorResponseDto, TradeRequest } from '../schemas';

import { orvalClient } from '../../lib/orval/orval.client';
import type { ErrorType, BodyType } from '../../lib/orval/orval.client';

/**
 * Verifies share availability in the specific account, credits the total value to user cash, and logs the sale.
 * @summary Execute a sell order
 */
export const sellStock = (
	tradeRequest: BodyType<TradeRequest>,
	signal?: AbortSignal
) => {
	return orvalClient<void>({
		url: `/trades/sell`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: tradeRequest,
		signal,
	});
};

export const getSellStockMutationOptions = <
	TError = ErrorType<Blob>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof sellStock>>,
		TError,
		{ data: BodyType<TradeRequest> },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof sellStock>>,
	TError,
	{ data: BodyType<TradeRequest> },
	TContext
> => {
	const mutationKey = ['sellStock'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof sellStock>>,
		{ data: BodyType<TradeRequest> }
	> = props => {
		const { data } = props ?? {};

		return sellStock(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SellStockMutationResult = NonNullable<
	Awaited<ReturnType<typeof sellStock>>
>;
export type SellStockMutationBody = BodyType<TradeRequest>;
export type SellStockMutationError = ErrorType<Blob>;

/**
 * @summary Execute a sell order
 */
export const useSellStock = <TError = ErrorType<Blob>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof sellStock>>,
			TError,
			{ data: BodyType<TradeRequest> },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof sellStock>>,
	TError,
	{ data: BodyType<TradeRequest> },
	TContext
> => {
	return useMutation(getSellStockMutationOptions(options), queryClient);
};
/**
 * Validates user cash balance, fetches real-time asset price via Brapi, updates average cost, and persists the transaction log.
 * @summary Execute a buy order
 */
export const buyStock = (
	tradeRequest: BodyType<TradeRequest>,
	signal?: AbortSignal
) => {
	return orvalClient<unknown>({
		url: `/trades/buy`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: tradeRequest,
		signal,
	});
};

export const getBuyStockMutationOptions = <
	TError = ErrorType<ErrorResponseDto>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof buyStock>>,
		TError,
		{ data: BodyType<TradeRequest> },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof buyStock>>,
	TError,
	{ data: BodyType<TradeRequest> },
	TContext
> => {
	const mutationKey = ['buyStock'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof buyStock>>,
		{ data: BodyType<TradeRequest> }
	> = props => {
		const { data } = props ?? {};

		return buyStock(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type BuyStockMutationResult = NonNullable<
	Awaited<ReturnType<typeof buyStock>>
>;
export type BuyStockMutationBody = BodyType<TradeRequest>;
export type BuyStockMutationError = ErrorType<ErrorResponseDto>;

/**
 * @summary Execute a buy order
 */
export const useBuyStock = <
	TError = ErrorType<ErrorResponseDto>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof buyStock>>,
			TError,
			{ data: BodyType<TradeRequest> },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof buyStock>>,
	TError,
	{ data: BodyType<TradeRequest> },
	TContext
> => {
	return useMutation(getBuyStockMutationOptions(options), queryClient);
};
/**
 * Calculates total equity (Cash + Market Value of Assets) for a specific account using real-time market data.
 * @summary Get consolidated portfolio for account
 */
export const getAccountPortfolio = (
	accountId: string,
	signal?: AbortSignal
) => {
	return orvalClient<Blob>({
		url: `/trades/portfolio/${accountId}`,
		method: 'GET',
		responseType: 'blob',
		signal,
	});
};

export const getGetAccountPortfolioQueryKey = (accountId: string) => {
	return [`/trades/portfolio/${accountId}`] as const;
};

export const getGetAccountPortfolioQueryOptions = <
	TData = Awaited<ReturnType<typeof getAccountPortfolio>>,
	TError = ErrorType<Blob>,
>(
	accountId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getAccountPortfolio>>,
				TError,
				TData
			>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetAccountPortfolioQueryKey(accountId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getAccountPortfolio>>
	> = ({ signal }) => getAccountPortfolio(accountId, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!accountId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getAccountPortfolio>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAccountPortfolioQueryResult = NonNullable<
	Awaited<ReturnType<typeof getAccountPortfolio>>
>;
export type GetAccountPortfolioQueryError = ErrorType<Blob>;

export function useGetAccountPortfolio<
	TData = Awaited<ReturnType<typeof getAccountPortfolio>>,
	TError = ErrorType<Blob>,
>(
	accountId: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getAccountPortfolio>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAccountPortfolio>>,
					TError,
					Awaited<ReturnType<typeof getAccountPortfolio>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAccountPortfolio<
	TData = Awaited<ReturnType<typeof getAccountPortfolio>>,
	TError = ErrorType<Blob>,
>(
	accountId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getAccountPortfolio>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAccountPortfolio>>,
					TError,
					Awaited<ReturnType<typeof getAccountPortfolio>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAccountPortfolio<
	TData = Awaited<ReturnType<typeof getAccountPortfolio>>,
	TError = ErrorType<Blob>,
>(
	accountId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getAccountPortfolio>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get consolidated portfolio for account
 */

export function useGetAccountPortfolio<
	TData = Awaited<ReturnType<typeof getAccountPortfolio>>,
	TError = ErrorType<Blob>,
>(
	accountId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getAccountPortfolio>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetAccountPortfolioQueryOptions(accountId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns a chronological list of all buy and sell operations performed by the authenticated user. Dates are formatted for Brasilia timezone.
 * @summary Get transaction history
 */
export const getTransactionHistory = (signal?: AbortSignal) => {
	return orvalClient<Blob>({
		url: `/trades/history`,
		method: 'GET',
		responseType: 'blob',
		signal,
	});
};

export const getGetTransactionHistoryQueryKey = () => {
	return [`/trades/history`] as const;
};

export const getGetTransactionHistoryQueryOptions = <
	TData = Awaited<ReturnType<typeof getTransactionHistory>>,
	TError = ErrorType<Blob>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getTransactionHistory>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetTransactionHistoryQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getTransactionHistory>>
	> = ({ signal }) => getTransactionHistory(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getTransactionHistory>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTransactionHistoryQueryResult = NonNullable<
	Awaited<ReturnType<typeof getTransactionHistory>>
>;
export type GetTransactionHistoryQueryError = ErrorType<Blob>;

export function useGetTransactionHistory<
	TData = Awaited<ReturnType<typeof getTransactionHistory>>,
	TError = ErrorType<Blob>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTransactionHistory>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getTransactionHistory>>,
					TError,
					Awaited<ReturnType<typeof getTransactionHistory>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionHistory<
	TData = Awaited<ReturnType<typeof getTransactionHistory>>,
	TError = ErrorType<Blob>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTransactionHistory>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getTransactionHistory>>,
					TError,
					Awaited<ReturnType<typeof getTransactionHistory>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionHistory<
	TData = Awaited<ReturnType<typeof getTransactionHistory>>,
	TError = ErrorType<Blob>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTransactionHistory>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get transaction history
 */

export function useGetTransactionHistory<
	TData = Awaited<ReturnType<typeof getTransactionHistory>>,
	TError = ErrorType<Blob>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTransactionHistory>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetTransactionHistoryQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
