/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type {
	AccountResponseDto,
	CreateAccountDto,
	UpdateUserDto,
	User,
} from '../schemas';

import { orvalClient } from '../../lib/orval/orval.client';
import type { ErrorType, BodyType } from '../../lib/orval/orval.client';

/**
 * Retrieves user details based on the provided user ID.
 * @summary Search user by ID.
 */
export const getUserById = (userId: string, signal?: AbortSignal) => {
	return orvalClient<User>({ url: `/users/${userId}`, method: 'GET', signal });
};

export const getGetUserByIdQueryKey = (userId: string) => {
	return [`/users/${userId}`] as const;
};

export const getGetUserByIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<void>,
>(
	userId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetUserByIdQueryKey(userId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = ({
		signal,
	}) => getUserById(userId, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!userId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getUserById>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserByIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUserById>>
>;
export type GetUserByIdQueryError = ErrorType<void>;

export function useGetUserById<
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<void>,
>(
	userId: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserById>>,
					TError,
					Awaited<ReturnType<typeof getUserById>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserById<
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<void>,
>(
	userId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserById>>,
					TError,
					Awaited<ReturnType<typeof getUserById>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserById<
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<void>,
>(
	userId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search user by ID.
 */

export function useGetUserById<
	TData = Awaited<ReturnType<typeof getUserById>>,
	TError = ErrorType<void>,
>(
	userId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUserByIdQueryOptions(userId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Updates the information of an existing user based on the provided user ID and new data.
 * @summary Update a user's data.
 */
export const updateUserById = (
	userId: string,
	updateUserDto: BodyType<UpdateUserDto>,
	signal?: AbortSignal
) => {
	return orvalClient<void>({
		url: `/users/${userId}`,
		method: 'PUT',
		headers: { 'Content-Type': 'application/json' },
		data: updateUserDto,
		signal,
	});
};

export const getUpdateUserByIdMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateUserById>>,
		TError,
		{ userId: string; data: BodyType<UpdateUserDto> },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateUserById>>,
	TError,
	{ userId: string; data: BodyType<UpdateUserDto> },
	TContext
> => {
	const mutationKey = ['updateUserById'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateUserById>>,
		{ userId: string; data: BodyType<UpdateUserDto> }
	> = props => {
		const { userId, data } = props ?? {};

		return updateUserById(userId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateUserByIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateUserById>>
>;
export type UpdateUserByIdMutationBody = BodyType<UpdateUserDto>;
export type UpdateUserByIdMutationError = ErrorType<void>;

/**
 * @summary Update a user's data.
 */
export const useUpdateUserById = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateUserById>>,
			TError,
			{ userId: string; data: BodyType<UpdateUserDto> },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof updateUserById>>,
	TError,
	{ userId: string; data: BodyType<UpdateUserDto> },
	TContext
> => {
	return useMutation(getUpdateUserByIdMutationOptions(options), queryClient);
};
/**
 * Deletes a user based on the provided user ID.
 * @summary Remove a user from the system.
 */
export const deleteUser = (userId: string, signal?: AbortSignal) => {
	return orvalClient<void>({
		url: `/users/${userId}`,
		method: 'DELETE',
		signal,
	});
};

export const getDeleteUserMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteUser>>,
		TError,
		{ userId: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteUser>>,
	TError,
	{ userId: string },
	TContext
> => {
	const mutationKey = ['deleteUser'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteUser>>,
		{ userId: string }
	> = props => {
		const { userId } = props ?? {};

		return deleteUser(userId);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteUser>>
>;

export type DeleteUserMutationError = ErrorType<unknown>;

/**
 * @summary Remove a user from the system.
 */
export const useDeleteUser = <TError = ErrorType<unknown>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteUser>>,
			TError,
			{ userId: string },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof deleteUser>>,
	TError,
	{ userId: string },
	TContext
> => {
	return useMutation(getDeleteUserMutationOptions(options), queryClient);
};
/**
 * Retrieves all investment accounts associated with a user, including the full list of stocks and their real-time market prices.
 * @summary List all accounts with their portfolios.
 */
export const listAllAccounts = (userId: string, signal?: AbortSignal) => {
	return orvalClient<AccountResponseDto[]>({
		url: `/users/${userId}/accounts`,
		method: 'GET',
		signal,
	});
};

export const getListAllAccountsQueryKey = (userId: string) => {
	return [`/users/${userId}/accounts`] as const;
};

export const getListAllAccountsQueryOptions = <
	TData = Awaited<ReturnType<typeof listAllAccounts>>,
	TError = ErrorType<void>,
>(
	userId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listAllAccounts>>,
				TError,
				TData
			>
		>;
	}
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListAllAccountsQueryKey(userId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllAccounts>>> = ({
		signal,
	}) => listAllAccounts(userId, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!userId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof listAllAccounts>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAllAccountsQueryResult = NonNullable<
	Awaited<ReturnType<typeof listAllAccounts>>
>;
export type ListAllAccountsQueryError = ErrorType<void>;

export function useListAllAccounts<
	TData = Awaited<ReturnType<typeof listAllAccounts>>,
	TError = ErrorType<void>,
>(
	userId: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listAllAccounts>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listAllAccounts>>,
					TError,
					Awaited<ReturnType<typeof listAllAccounts>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllAccounts<
	TData = Awaited<ReturnType<typeof listAllAccounts>>,
	TError = ErrorType<void>,
>(
	userId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listAllAccounts>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listAllAccounts>>,
					TError,
					Awaited<ReturnType<typeof listAllAccounts>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllAccounts<
	TData = Awaited<ReturnType<typeof listAllAccounts>>,
	TError = ErrorType<void>,
>(
	userId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listAllAccounts>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all accounts with their portfolios.
 */

export function useListAllAccounts<
	TData = Awaited<ReturnType<typeof listAllAccounts>>,
	TError = ErrorType<void>,
>(
	userId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listAllAccounts>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListAllAccountsQueryOptions(userId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Opens a new investment portfolio associated with the user and sets the billing address.
 * @summary Create an account for the user.
 */
export const createAccount = (
	userId: string,
	createAccountDto: BodyType<CreateAccountDto>,
	signal?: AbortSignal
) => {
	return orvalClient<void>({
		url: `/users/${userId}/accounts`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: createAccountDto,
		signal,
	});
};

export const getCreateAccountMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createAccount>>,
		TError,
		{ userId: string; data: BodyType<CreateAccountDto> },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createAccount>>,
	TError,
	{ userId: string; data: BodyType<CreateAccountDto> },
	TContext
> => {
	const mutationKey = ['createAccount'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createAccount>>,
		{ userId: string; data: BodyType<CreateAccountDto> }
	> = props => {
		const { userId, data } = props ?? {};

		return createAccount(userId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateAccountMutationResult = NonNullable<
	Awaited<ReturnType<typeof createAccount>>
>;
export type CreateAccountMutationBody = BodyType<CreateAccountDto>;
export type CreateAccountMutationError = ErrorType<unknown>;

/**
 * @summary Create an account for the user.
 */
export const useCreateAccount = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createAccount>>,
			TError,
			{ userId: string; data: BodyType<CreateAccountDto> },
			TContext
		>;
	},
	queryClient?: QueryClient
): UseMutationResult<
	Awaited<ReturnType<typeof createAccount>>,
	TError,
	{ userId: string; data: BodyType<CreateAccountDto> },
	TContext
> => {
	return useMutation(getCreateAccountMutationOptions(options), queryClient);
};
/**
 * Retrieves a list of all users registered in the system.
 * @summary Lists all registered users.
 */
export const listAllUsers = (signal?: AbortSignal) => {
	return orvalClient<User[]>({ url: `/users/all`, method: 'GET', signal });
};

export const getListAllUsersQueryKey = () => {
	return [`/users/all`] as const;
};

export const getListAllUsersQueryOptions = <
	TData = Awaited<ReturnType<typeof listAllUsers>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof listAllUsers>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListAllUsersQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllUsers>>> = ({
		signal,
	}) => listAllUsers(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listAllUsers>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAllUsersQueryResult = NonNullable<
	Awaited<ReturnType<typeof listAllUsers>>
>;
export type ListAllUsersQueryError = ErrorType<unknown>;

export function useListAllUsers<
	TData = Awaited<ReturnType<typeof listAllUsers>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAllUsers>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listAllUsers>>,
					TError,
					Awaited<ReturnType<typeof listAllUsers>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllUsers<
	TData = Awaited<ReturnType<typeof listAllUsers>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAllUsers>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listAllUsers>>,
					TError,
					Awaited<ReturnType<typeof listAllUsers>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllUsers<
	TData = Awaited<ReturnType<typeof listAllUsers>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAllUsers>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Lists all registered users.
 */

export function useListAllUsers<
	TData = Awaited<ReturnType<typeof listAllUsers>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listAllUsers>>, TError, TData>
		>;
	},
	queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListAllUsersQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
