/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import type { Account } from './account';
import type { AccountStockId } from './accountStockId';
import type { Stock } from './stock';

export interface AccountStock {
	id?: AccountStockId;
	account?: Account;
	stock?: Stock;
	quantity?: number;
	averagePrice?: number;
}
