/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import type { AccountStock } from './accountStock';
import type { BillingAddress } from './billingAddress';
import type { User } from './user';

export interface Account {
	accountId?: string;
	user?: User;
	billingAddress?: BillingAddress;
	description?: string;
	accountStocks?: AccountStock[];
}
