/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import type { AccountStockResponseDto } from './accountStockResponseDto';

/**
 * Response with user account details.
 */
export interface AccountResponseDto {
	/** Unique identifier of the account. */
	accountId: string;
	/** Friendly description of the account. */
	description: string;
	stocks?: AccountStockResponseDto[];
}
