/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Represents a stock position in the user's portfolio.
 */
export interface AccountStockResponseDto {
	/** Stock ticker symbol. */
	stockId: string;
	/** Name of the company issuing the stock. */
	name: string;
	/** Full name of the company issuing the stock. */
	longName: string;
	/** Industry */
	sector: string;
	/** Total quantity of the stock in the portfolio. */
	quantity: number;
	/** Average purchase price (User cost) */
	avgPrice: number;
	/** Current market price (Brapi) */
	currentPrice: number;
	/** Percentage change on the day */
	change: number;
	/** Daily trading volume */
	volume: number;
	/** Total value at market price (Qty * CurrentPrice) */
	marketValue: number;
	/** Total amount invested in the stock (quantity x average price). */
	total: number;
	/** URL of the logo of the company issuing the stock. */
	logoUrl: string;
}
