/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Data Transfer Object representing the total financial balance of an account.
 */
export interface AccountBalanceDto {
	/** Unique identifier of the account (UUID). */
	accountId?: string;
	/** The sum of all assets in the account, multiplied by their current market price. */
	totalBalance?: number;
	/** The exact moment the balance was calculated based on real-time data. */
	updatedAt?: string;
}
