/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Request payload to associate a stock with an account
 */
export interface AssociateAccountStockDto {
	/** Stock trading code (ticker) to be associated with the account */
	stockId: string;
	/**
	 * Number of shares to associate with the account
	 * @minimum 1
	 */
	quantity: number;
}
