/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import type { UserDto } from './userDto';

/**
 * Response after a successful login
 */
export interface AuthResponseDto {
	/** JWT token used for authenticated requests */
	accessToken: string;
	/** The authenticated user details */
	user: UserDto;
}
