/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Request payload to create a new account.
 */
export interface CreateAccountDto {
	/** Human-readable description of the account. */
	description: string;
	/** Street name of the account address. */
	street: string;
	/**
	 * Street number of the account address.
	 * @minimum 1
	 */
	number: number;
}
