/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Request payload to create a new stock
 */
export interface CreateStockDto {
	/**
	 * Stock trading code (ticker)
	 * @minLength 4
	 * @maxLength 10
	 */
	stockId: string;
	/** Company legal or trade name */
	description: string;
}
