/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Request payload to create a new user
 */
export interface CreateUserDto {
	/** Unique username used to identify the user in the system */
	username: string;
	/** Valid email address of the user */
	email: string;
	/**
	 * User password with a minimum of 8 characters
	 * @minLength 8
	 * @maxLength 2147483647
	 */
	password: string;
}
