/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import type { ErrorResponseDtoFieldsErrors } from './errorResponseDtoFieldsErrors';

/**
 * Standardized object for returning API error details.
 */
export interface ErrorResponseDto {
	/** HTTP Status Code. */
	status: number;
	/** General error message */
	message: string;
	/** Timestamp when the error occurred */
	timestamp: string;
	/** Map containing specific field names and their respective validation error messages. Can be null if not a validation error. */
	fieldsErrors?: ErrorResponseDtoFieldsErrors;
}
