/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Map containing specific field names and their respective validation error messages. Can be null if not a validation error.
 */
export type ErrorResponseDtoFieldsErrors = { [key: string]: string };
