/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Data required to authenticate a user and generate a JWT access token.
 */
export interface LoginDto {
	/** The unique username used during registration. */
	username: string;
	/** The user's password in plain text. It will be validated against the stored hash. */
	password: string;
}
