/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Detailed breakdown of the user's financial standing.
 */
export interface PortfolioResponseDto {
	/** User's liquid cash available in the platform. */
	availableCash?: number;
	/** Market value sum of all owned stocks. */
	investedInStocks?: number;
	/** Total equity (cash + stocks). */
	totalEquity?: number;
	/** Timestamp of the real-time calculation. */
	updatedAt?: string;
}
