/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

export interface Stock {
	stockId?: string;
	name?: string;
	longName?: string;
	sector?: string;
	logoUrl?: string;
	description?: string;
}
