/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Parameters required to perform an asset trading operation (Buy or Sell).
 */
export interface TradeRequest {
	/**
	 * Asset symbol on the stock exchange (ticker). It must be a valid ticker on Brapi.
	 * @minLength 3
	 * @maxLength 10
	 */
	stockId: string;
	/**
	 * Number of shares to be traded. Must be a positive integer.
	 * @minimum 1
	 */
	quantity: number;
	/** Unique ID of the wallet (Account) where custody will be changed. */
	accountId: string;
}
