/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Type of the trade operation.
 */
export type TransactionResponseType =
	(typeof TransactionResponseType)[keyof typeof TransactionResponseType];

export const TransactionResponseType = {
	BUY: 'BUY',
	SELL: 'SELL',
} as const;
