/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import type { TransactionResponseType } from './transactionResponseType';

/**
 * Model representing a historical stock market transaction (Buy/Sell) for account statements.
 */
export interface TransactionResponse {
	/** Unique identifier of the transaction in the database. */
	transactionId: string;
	/** Ticker symbol of the asset traded. */
	stockId: string;
	/** Type of the trade operation. */
	type: TransactionResponseType;
	/** Number of units (shares) traded in this specific operation. */
	quantity: number;
	/** Unit price of the asset at the exact time of the transaction. */
	priceAtTime: number;
	/** Total monetary value of the operation (Quantity * PriceAtTime). */
	totalValue: number;
	/** The precise date and time when the transaction was processed and persisted. */
	timestamp: string;
}
