/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Request payload to update user information.
 */
export interface UpdateUserDto {
	/** New username to replace the current one. */
	username?: string;
	/**
	 * New user password with a minimum of 8 characters.
	 * @minLength 8
	 * @maxLength 2147483647
	 */
	password?: string;
}
