/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import type { UserDtoRole } from './userDtoRole';

/**
 * Represents the authenticated user.
 */
export interface UserDto {
	/** Unique identifier of the user. */
	userId: string;
	/** Unique username used to identify the user in the system. */
	username: string;
	/** User email address. */
	email: string;
	/** Role or profile assigned to the user. */
	role: UserDtoRole;
}
