/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */
import type { Account } from './account';
import type { UserRole } from './userRole';

export interface User {
	userId?: string;
	username?: string;
	email?: string;
	password?: string;
	role?: UserRole;
	creationTimestamp?: string;
	updateTimestamp?: string;
	accounts?: Account[];
}
