/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Summary of a stock owned by the user
 */
export interface UserStockSummaryDto {
	stockId?: string;
	/** Total quantity owned across all accounts */
	totalQuantity?: number;
}
