/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Investment Aggregator API
 * System for managing stock portfolios with real-time integration via Brapi.
 * OpenAPI spec version: 1.0
 */

/**
 * Role or profile assigned to the user
 */
export type UserDtoRole = (typeof UserDtoRole)[keyof typeof UserDtoRole];

export const UserDtoRole = {
	ADMIN: 'ADMIN',
} as const;
